define aradia = Character(name="ARADIA", what_color="burgundy", kind=pesterchum, image="aradia")

image aradia BIG-smile = Image("{{assets}}/sprite/aradia_BIG-smile.png", ypos=730)
image aradia blank = Image("{{assets}}/sprite/aradia_blank.png", ypos=730)
image aradia confused = Image("{{assets}}/sprite/aradia_confused.png", ypos=730)
image aradia ghost = Image("{{assets}}/sprite/aradia_ghost.png", ypos=730)
image aradia gt amused = Image("{{assets}}/sprite/aradia_gt_amused.png", ypos=730)
image aradia gt biggersmile-2 = Image("{{assets}}/sprite/aradia_gt_biggersmile-2.png", ypos=730)
image aradia gt biggersmile = Image("{{assets}}/sprite/aradia_gt_biggersmile.png", ypos=730)
image aradia gt bothered = Image("{{assets}}/sprite/aradia_gt_bothered.png", ypos=730)
image aradia gt confused = Image("{{assets}}/sprite/aradia_gt_confused.png", ypos=730)
image aradia gt disgusted = Image("{{assets}}/sprite/aradia_gt_disgusted.png", ypos=730)
image aradia gt mm = Image("{{assets}}/sprite/aradia_gt_mm.png", ypos=730)
image aradia gt oh = Image("{{assets}}/sprite/aradia_gt_oh.png", ypos=730)
image aradia gt ohno = Image("{{assets}}/sprite/aradia_gt_ohno.png", ypos=730)
image aradia gt sad = Image("{{assets}}/sprite/aradia_gt_sad.png", ypos=730)
image aradia gt smile = Image("{{assets}}/sprite/aradia_gt_smile.png", ypos=730)
image aradia gt smile2 = Image("{{assets}}/sprite/aradia_gt_smile2.png", ypos=730)
image aradia gt talk = Image("{{assets}}/sprite/aradia_gt_talk.png", ypos=730)
image aradia serious = Image("{{assets}}/sprite/aradia_serious.png", ypos=730)
image aradia soft-smile = Image("{{assets}}/sprite/aradia_soft-smile.png", ypos=730)
image aradia surprised = Image("{{assets}}/sprite/aradia_surprised.png", ypos=730)
image aradia turned = Image("{{assets}}/sprite/aradia_turned.png", ypos=730)
image aradia uhh = Image("{{assets}}/sprite/aradia_uhh.png", ypos=730)
image aradia uhh2 = Image("{{assets}}/sprite/aradia_uhh2.png", ypos=730)
image aradia worried = Image("{{assets}}/sprite/aradia_worried.png", ypos=730)
