define equius = Character(name="EQUIUS", what_color="indigo", kind=pesterchum, image="equius")

image equius angry = Image("{{assets}}/sprite/equius_angry.png", ypos=730)
image equius arms crossed = Image("{{assets}}/sprite/equius_arms_crossed.png", ypos=730)
image equius back turned = Image("{{assets}}/sprite/equius_back_turned.png", ypos=730)
image equius embarrassed = Image("{{assets}}/sprite/equius_embarrassed.png", ypos=730)
image equius forced smile = Image("{{assets}}/sprite/equius_forced_smile.png", ypos=730)
image equius nervous = Image("{{assets}}/sprite/equius_nervous.png", ypos=730)
image equius normal smile = Image("{{assets}}/sprite/equius_normal_smile.png", ypos=730)
image equius punching = Image("{{assets}}/sprite/equius_punching.png", ypos=730)
image equius punching younger = Image("{{assets}}/sprite/equius_punching_younger.png", ypos=730)
image equius raised eyebrows = Image("{{assets}}/sprite/equius_raised_eyebrows.png", ypos=730)
image equius relaxed = Image("{{assets}}/sprite/equius_relaxed.png", ypos=730)
image equius relaxed younger = Image("{{assets}}/sprite/equius_relaxed_younger.png", ypos=730)
image equius serious = Image("{{assets}}/sprite/equius_serious.png", ypos=730)
image equius shocked = Image("{{assets}}/sprite/equius_shocked.png", ypos=730)
image equius surprised = Image("{{assets}}/sprite/equius_surprised.png", ypos=730)
image equius sweating = Image("{{assets}}/sprite/equius_sweating.png", ypos=730)
image equius tense = Image("{{assets}}/sprite/equius_tense.png", ypos=730)
image equius thinking = Image("{{assets}}/sprite/equius_thinking.png", ypos=730)
image equius wiping nosweat = Image("{{assets}}/sprite/equius_wiping_nosweat.png", ypos=730)
image equius wiping sweat = Image("{{assets}}/sprite/equius_wiping_sweat.png", ypos=730)
