define feferi = Character(name="FEFERI", what_color="fuchsia", kind=pesterchum, image="feferi")

image feferi Concerned = Image("{{assets}}/sprite/Feferi_Concerned.png", ypos=730)
image feferi ConcernedTalk = Image("{{assets}}/sprite/Feferi_ConcernedTalk.png", ypos=730)
image feferi Dancing = Image("{{assets}}/sprite/Feferi_Dancing.png", ypos=730)
image feferi Disappointed = Image("{{assets}}/sprite/Feferi_Disappointed.png", ypos=730)
image feferi Excited = Image("{{assets}}/sprite/Feferi_Excited.png", ypos=730)
image feferi Fanning = Image("{{assets}}/sprite/Feferi_Fanning.png", ypos=730)
image feferi Frustrated = Image("{{assets}}/sprite/Feferi_Frustrated.png", ypos=730)
image feferi Glubbing = Image("{{assets}}/sprite/Feferi_Glubbing.png", ypos=730)
image feferi Idea = Image("{{assets}}/sprite/Feferi_Idea.png", ypos=730)
image feferi Neutral = Image("{{assets}}/sprite/Feferi_Neutral.png", ypos=730)
image feferi Proud = Image("{{assets}}/sprite/Feferi_Proud.png", ypos=730)
image feferi SittingAngry = Image("{{assets}}/sprite/Feferi_SittingAngry.png", ypos=730)
image feferi SittingAnxious = Image("{{assets}}/sprite/Feferi_SittingAnxious.png", ypos=730)
image feferi SittingBummed = Image("{{assets}}/sprite/Feferi_SittingBummed.png", ypos=730)
image feferi SittingExcited = Image("{{assets}}/sprite/Feferi_SittingExcited.png", ypos=730)
image feferi SittingHappy = Image("{{assets}}/sprite/Feferi_SittingHappy.png", ypos=730)
image feferi SittingSmiling = Image("{{assets}}/sprite/Feferi_SittingSmiling.png", ypos=730)
image feferi Swimming = Image("{{assets}}/sprite/Feferi_Swimming.png", ypos=730)
image feferi SwimmingBubble = Image("{{assets}}/sprite/Feferi_SwimmingBubble.png", ypos=730)
image feferi SwimmingInhale = Image("{{assets}}/sprite/Feferi_SwimmingInhale.png", ypos=730)
image feferi Thoughtful = Image("{{assets}}/sprite/Feferi_Thoughtful.png", ypos=730)
