define gamzee = Character(name="GAMZEE", what_color="purple", kind=pesterchum, image="gamzee")

image gamzee neutral 1 = Image("{{assets}}/sprite/gamzee_neutral_1.png", ypos=730)
image gamzee neutral 2 = Image("{{assets}}/sprite/gamzee_neutral_2.png", ypos=730)
image gamzee neutral 3 = Image("{{assets}}/sprite/gamzee_neutral_3.png", ypos=730)
image gamzee neutral 4 = Image("{{assets}}/sprite/gamzee_neutral_4.png", ypos=730)
image gamzee pie 1 = Image("{{assets}}/sprite/gamzee_pie_1.png", ypos=730)
image gamzee pie 2 = Image("{{assets}}/sprite/gamzee_pie_2.png", ypos=730)
image gamzee silhouette = Image("{{assets}}/sprite/gamzee_silhouette.png", ypos=730)
image gamzee sober 1 = Image("{{assets}}/sprite/gamzee_sober_1.png", ypos=730)
image gamzee sober 2 = Image("{{assets}}/sprite/gamzee_sober_2.png", ypos=730)
image gamzee surprised = Image("{{assets}}/sprite/gamzee_surprised.png", ypos=730)
image gamzee talk 1 = Image("{{assets}}/sprite/gamzee_talk_1.png", ypos=730)
image gamzee talk 2 = Image("{{assets}}/sprite/gamzee_talk_2.png", ypos=730)
image gamzee talk 3 = Image("{{assets}}/sprite/gamzee_talk_3.png", ypos=730)
image gamzee talk 4 = Image("{{assets}}/sprite/gamzee_talk_4.png", ypos=730)
image gamzee think = Image("{{assets}}/sprite/gamzee_think.png", ypos=730)
image gamzee toblerone 01 = Image("{{assets}}/sprite/gamzee_toblerone_01.png", ypos=730)
image gamzee toblerone 02 = Image("{{assets}}/sprite/gamzee_toblerone_02.png", ypos=730)
