define kanaya = Character(name="KANAYA", what_color="jade", kind=pesterchum, image="kanaya")

image kanaya bluh = Image("{{assets}}/sprite/Kanaya_bluh.png", ypos=730)
image kanaya chainsaw = Image("{{assets}}/sprite/Kanaya_chainsaw.png", ypos=730)
image kanaya chainsaw blood = Image("{{assets}}/sprite/Kanaya_chainsaw_blood.png", ypos=730)
image kanaya disappointed = Image("{{assets}}/sprite/Kanaya_disappointed.png", ypos=730)
image kanaya displease = Image("{{assets}}/sprite/Kanaya_displease.png", ypos=730)
image kanaya dubious = Image("{{assets}}/sprite/Kanaya_dubious.png", ypos=730)
image kanaya embarrased = Image("{{assets}}/sprite/Kanaya_embarrased.png", ypos=730)
image kanaya husktop = Image("{{assets}}/sprite/Kanaya_husktop.png", ypos=730)
image kanaya husktop angry = Image("{{assets}}/sprite/Kanaya_husktop_angry.png", ypos=730)
image kanaya husktop cancel = Image("{{assets}}/sprite/Kanaya_husktop_cancel.png", ypos=730)
image kanaya husktop devastated = Image("{{assets}}/sprite/Kanaya_husktop_devastated.png", ypos=730)
image kanaya husktop mad = Image("{{assets}}/sprite/Kanaya_husktop_mad.png", ypos=730)
image kanaya husktop surprised = Image("{{assets}}/sprite/Kanaya_husktop_surprised.png", ypos=730)
image kanaya moirailed = Image("{{assets}}/sprite/Kanaya_moirailed.png", ypos=730)
image kanaya neutral = Image("{{assets}}/sprite/Kanaya_neutral.png", ypos=730)
image kanaya pleased = Image("{{assets}}/sprite/Kanaya_pleased.png", ypos=730)
image kanaya sad = Image("{{assets}}/sprite/Kanaya_sad.png", ypos=730)
image kanaya suffering = Image("{{assets}}/sprite/Kanaya_suffering.png", ypos=730)
image kanaya surprise = Image("{{assets}}/sprite/Kanaya_surprise.png", ypos=730)
image kanaya talk = Image("{{assets}}/sprite/Kanaya_talk.png", ypos=730)
