define karkat = Character(name="KARKAT", what_color="gray", kind=pesterchum, image="karkat")

image karkat blanket = Image("{{assets}}/sprite/Karkat_blanket.png", ypos=730)
image karkat blanket fear = Image("{{assets}}/sprite/Karkat_blanket_fear.png", ypos=730)
image karkat blanket uneasy = Image("{{assets}}/sprite/Karkat_blanket_uneasy.png", ypos=730)
image karkat discuss = Image("{{assets}}/sprite/Karkat_discuss.png", ypos=730)
image karkat ew = Image("{{assets}}/sprite/Karkat_ew.png", ypos=730)
image karkat explaintome = Image("{{assets}}/sprite/Karkat_explaintome.png", ypos=730)
image karkat eyeroll = Image("{{assets}}/sprite/Karkat_eyeroll.png", ypos=730)
image karkat freaking out = Image("{{assets}}/sprite/Karkat_freaking_out.png", ypos=730)
image karkat neutral = Image("{{assets}}/sprite/Karkat_neutral.png", ypos=730)
image karkat shock = Image("{{assets}}/sprite/Karkat_shock.png", ypos=730)
image karkat shock blood = Image("{{assets}}/sprite/Karkat_shock_blood.png", ypos=730)
image karkat suspecting = Image("{{assets}}/sprite/Karkat_suspecting.png", ypos=730)
image karkat talk = Image("{{assets}}/sprite/Karkat_talk.png", ypos=730)
image karkat talk2 = Image("{{assets}}/sprite/Karkat_talk2.png", ypos=730)
image karkat talk3 = Image("{{assets}}/sprite/Karkat_talk3.png", ypos=730)
image karkat uneasy = Image("{{assets}}/sprite/Karkat_uneasy.png", ypos=730)
image karkat wtfisthis = Image("{{assets}}/sprite/Karkat_wtfisthis.png", ypos=730)
