define nepeta = Character(name="NEPETA", what_color="olive", kind=pesterchum, image="nepeta")

image nepeta Apex Pred = Image("{{assets}}/sprite/Nepeta_Apex_Pred.png", ypos=730)
image nepeta Apex Pred Grimace = Image("{{assets}}/sprite/Nepeta_Apex_Pred_Grimace.png", ypos=730)
image nepeta Downtrodden = Image("{{assets}}/sprite/Nepeta_Downtrodden.png", ypos=730)
image nepeta Downtrodden Talk = Image("{{assets}}/sprite/Nepeta_Downtrodden_Talk.png", ypos=730)
image nepeta Embarassed = Image("{{assets}}/sprite/Nepeta_Embarassed.png", ypos=730)
image nepeta Embarassed Talk = Image("{{assets}}/sprite/Nepeta_Embarassed_Talk.png", ypos=730)
image nepeta Fear = Image("{{assets}}/sprite/Nepeta_Fear.png", ypos=730)
image nepeta Frown = Image("{{assets}}/sprite/Nepeta_Frown.png", ypos=730)
image nepeta Frown Talk = Image("{{assets}}/sprite/Nepeta_Frown_Talk.png", ypos=730)
image nepeta Lick = Image("{{assets}}/sprite/Nepeta_Lick.png", ypos=730)
image nepeta Mad = Image("{{assets}}/sprite/Nepeta_Mad.png", ypos=730)
image nepeta Mad Talk = Image("{{assets}}/sprite/Nepeta_Mad_Talk.png", ypos=730)
image nepeta Neutral = Image("{{assets}}/sprite/Nepeta_Neutral.png", ypos=730)
image nepeta Nya a = Image("{{assets}}/sprite/Nepeta_Nya_a.png", ypos=730)
image nepeta Nya b = Image("{{assets}}/sprite/Nepeta_Nya_b.png", ypos=730)
image nepeta Nya Serious a = Image("{{assets}}/sprite/Nepeta_Nya_Serious_a.png", ypos=730)
image nepeta Nya Serious b = Image("{{assets}}/sprite/Nepeta_Nya_Serious_b.png", ypos=730)
image nepeta Nya Talk a = Image("{{assets}}/sprite/Nepeta_Nya_Talk_a.png", ypos=730)
image nepeta Nya Talk b = Image("{{assets}}/sprite/Nepeta_Nya_Talk_b.png", ypos=730)
image nepeta Nya Tilt a = Image("{{assets}}/sprite/Nepeta_Nya_Tilt_a.png", ypos=730)
image nepeta Nya Tilt Happy a = Image("{{assets}}/sprite/Nepeta_Nya_Tilt_Happy_a.png", ypos=730)
image nepeta Nya Tilt Talk a = Image("{{assets}}/sprite/Nepeta_Nya_Tilt_Talk_a.png", ypos=730)
image nepeta Pout = Image("{{assets}}/sprite/Nepeta_Pout.png", ypos=730)
image nepeta Pout Talk = Image("{{assets}}/sprite/Nepeta_Pout_Talk.png", ypos=730)
image nepeta Sad = Image("{{assets}}/sprite/Nepeta_Sad.png", ypos=730)
image nepeta Sad Talk = Image("{{assets}}/sprite/Nepeta_Sad_Talk.png", ypos=730)
image nepeta Surprised = Image("{{assets}}/sprite/Nepeta_Surprised.png", ypos=730)
image nepeta Talk = Image("{{assets}}/sprite/Nepeta_Talk.png", ypos=730)
image nepeta Think 1 a = Image("{{assets}}/sprite/Nepeta_Think_1_a.png", ypos=730)
image nepeta Think 1 b = Image("{{assets}}/sprite/Nepeta_Think_1_b.png", ypos=730)
image nepeta Think 2 a = Image("{{assets}}/sprite/Nepeta_Think_2_a.png", ypos=730)
image nepeta Think 2 b = Image("{{assets}}/sprite/Nepeta_Think_2_b.png", ypos=730)
image nepeta Think 3 a = Image("{{assets}}/sprite/Nepeta_Think_3_a.png", ypos=730)
image nepeta Think 3 b = Image("{{assets}}/sprite/Nepeta_Think_3_b.png", ypos=730)
image nepeta Think 4 b = Image("{{assets}}/sprite/Nepeta_Think_4_b.png", ypos=730)
