define sollux = Character(name="SOLLUX", what_color="gold", kind=pesterchum, image="sollux")

image sollux analytical = Image("{{assets}}/sprite/sollux_analytical.png", ypos=730)
image sollux arguing = Image("{{assets}}/sprite/sollux_arguing.png", ypos=730)
image sollux critique = Image("{{assets}}/sprite/sollux_critique.png", ypos=730)
image sollux disgusted = Image("{{assets}}/sprite/sollux_disgusted.png", ypos=730)
image sollux letdown = Image("{{assets}}/sprite/sollux_letdown.png", ypos=730)
image sollux lostinthought = Image("{{assets}}/sprite/sollux_lostinthought.png", ypos=730)
image sollux nervous = Image("{{assets}}/sprite/sollux_nervous.png", ypos=730)
image sollux neutral = Image("{{assets}}/sprite/sollux_neutral.png", ypos=730)
image sollux phone = Image("{{assets}}/sprite/sollux_phone.png", ypos=730)
image sollux pissed = Image("{{assets}}/sprite/sollux_pissed.png", ypos=730)
image sollux psionic = Image("{{assets}}/sprite/sollux_psionic.png", ypos=730)
image sollux relax = Image("{{assets}}/sprite/sollux_relax.png", ypos=730)
image sollux scared = Image("{{assets}}/sprite/sollux_scared.png", ypos=730)
image sollux smile = Image("{{assets}}/sprite/sollux_smile.png", ypos=730)
image sollux smiletalk = Image("{{assets}}/sprite/sollux_smiletalk.png", ypos=730)
image sollux smug = Image("{{assets}}/sprite/sollux_smug.png", ypos=730)
image sollux talk = Image("{{assets}}/sprite/sollux_talk.png", ypos=730)
image sollux unimpressed = Image("{{assets}}/sprite/sollux_unimpressed.png", ypos=730)
