define tavros = Character(name="TAVROS", what_color="bronze", kind=pesterchum, image="tavros")

image tavros annoyed = Image("{{assets}}/sprite/tavros_annoyed.png", ypos=730)
image tavros areyoukiddingme = Image("{{assets}}/sprite/tavros_areyoukiddingme.png", ypos=730)
image tavros handwave = Image("{{assets}}/sprite/tavros_handwave.png", ypos=730)
image tavros mad = Image("{{assets}}/sprite/tavros_mad.png", ypos=730)
image tavros neutral = Image("{{assets}}/sprite/tavros_neutral.png", ypos=730)
image tavros ohgodno = Image("{{assets}}/sprite/tavros_ohgodno.png", ypos=730)
image tavros prospit happy = Image("{{assets}}/sprite/tavros_prospit_happy.png", ypos=730)
image tavros prospit pleased = Image("{{assets}}/sprite/tavros_prospit_pleased.png", ypos=730)
image tavros prospit surprised = Image("{{assets}}/sprite/tavros_prospit_surprised.png", ypos=730)
image tavros prospit uHHHH = Image("{{assets}}/sprite/tavros_prospit_uHHHH.png", ypos=730)
image tavros sheepish = Image("{{assets}}/sprite/tavros_sheepish.png", ypos=730)
image tavros shocked = Image("{{assets}}/sprite/tavros_shocked.png", ypos=730)
image tavros smug = Image("{{assets}}/sprite/tavros_smug.png", ypos=730)
image tavros tearsofjoy = Image("{{assets}}/sprite/tavros_tearsofjoy.png", ypos=730)
image tavros terrified = Image("{{assets}}/sprite/tavros_terrified.png", ypos=730)
image tavros uncomfortable = Image("{{assets}}/sprite/tavros_uncomfortable.png", ypos=730)
image tavros VERYsad = Image("{{assets}}/sprite/tavros_VERYsad.png", ypos=730)
image tavros wink = Image("{{assets}}/sprite/tavros_wink.png", ypos=730)
image tavros worried = Image("{{assets}}/sprite/tavros_worried.png", ypos=730)
