define terezi = Character(name="TEREZI", what_color="teal", kind=pesterchum, image="terezi")

image terezi angry = Image("{{assets}}/sprite/terezi_angry.png", ypos=730)
image terezi bitter = Image("{{assets}}/sprite/terezi_bitter.png", ypos=730)
image terezi brooding = Image("{{assets}}/sprite/terezi_brooding.png", ypos=730)
image terezi brooding talking = Image("{{assets}}/sprite/terezi_brooding_talking.png", ypos=730)
image terezi coin = Image("{{assets}}/sprite/terezi_coin.png", ypos=730)
image terezi concerned = Image("{{assets}}/sprite/terezi_concerned.png", ypos=730)
image terezi dark = Image("{{assets}}/sprite/terezi_dark.png", ypos=730)
image terezi flip = Image("{{assets}}/sprite/terezi_flip.png", ypos=730)
image terezi flip coinless = Image("{{assets}}/sprite/terezi_flip_coinless.png", ypos=730)
image terezi frown = Image("{{assets}}/sprite/terezi_frown.png", ypos=730)
image terezi laughing = Image("{{assets}}/sprite/terezi_laughing.png", ypos=730)
image terezi licking = Image("{{assets}}/sprite/terezi_licking.png", ypos=730)
image terezi neutral = Image("{{assets}}/sprite/terezi_neutral.png", ypos=730)
image terezi passionate = Image("{{assets}}/sprite/terezi_passionate.png", ypos=730)
image terezi pleased = Image("{{assets}}/sprite/terezi_pleased.png", ypos=730)
image terezi pleased talking = Image("{{assets}}/sprite/terezi_pleased_talking.png", ypos=730)
image terezi pointing = Image("{{assets}}/sprite/terezi_pointing.png", ypos=730)
image terezi presenting = Image("{{assets}}/sprite/terezi_presenting.png", ypos=730)
image terezi puzzled = Image("{{assets}}/sprite/terezi_puzzled.png", ypos=730)
image terezi serious = Image("{{assets}}/sprite/terezi_serious.png", ypos=730)
image terezi serious talking = Image("{{assets}}/sprite/terezi_serious_talking.png", ypos=730)
image terezi shrug = Image("{{assets}}/sprite/terezi_shrug.png", ypos=730)
image terezi sigh = Image("{{assets}}/sprite/terezi_sigh.png", ypos=730)
image terezi surprised = Image("{{assets}}/sprite/terezi_surprised.png", ypos=730)
image terezi thinking = Image("{{assets}}/sprite/terezi_thinking.png", ypos=730)
image terezi threatening = Image("{{assets}}/sprite/terezi_threatening.png", ypos=730)
image terezi upset = Image("{{assets}}/sprite/terezi_upset.png", ypos=730)
