init offset = 1
image fs_daraya burnitdown = "{{assets}}/sprite/daraya_burnitdown.png"
image fs_daraya comeon = "{{assets}}/sprite/daraya_comeon.png"
image fs_daraya elwurdspcool = "{{assets}}/sprite/daraya_elwurdspcool.png"
image fs_daraya eyeroll = "{{assets}}/sprite/daraya_eyeroll.png"
image fs_daraya frozen = "{{assets}}/sprite/daraya_frozen.png"
image fs_daraya frustrated = "{{assets}}/sprite/daraya_frustrated.png"
image fs_daraya gross = "{{assets}}/sprite/daraya_gross.png"
image fs_daraya oldbuildingsarekindasick = "{{assets}}/sprite/daraya_oldbuildingsarekindasick.png"
image fs_daraya quirkedup = "{{assets}}/sprite/daraya_quirkedup.png"
image fs_daraya sogoodriddance = "{{assets}}/sprite/daraya_sogoodriddance.png"
image fs_daraya takemewithyou = "{{assets}}/sprite/daraya_takemewithyou.png"
image fs_daraya trapped = "{{assets}}/sprite/daraya_trapped.png"
image fs_daraya ughitsyou = "{{assets}}/sprite/daraya_ughitsyou.png"
image fs_daraya uhhyouknowwhat = "{{assets}}/sprite/daraya_uhhyouknowwhat.png"
image fs_daraya upset = "{{assets}}/sprite/daraya_upset.png"
image fs_daraya well = "{{assets}}/sprite/daraya_well.png"
image fs_daraya whatever = "{{assets}}/sprite/daraya_whatever.png"
image fs_daraya WHOCARES = "{{assets}}/sprite/daraya_WHOCARES.png"
define fs_daraya = Character(name="DARAYA", kind=hiveswap, image="daraya", show_blood="jade")

