init offset = 1
image fs_diemen cry = "{{assets}}/sprite/diemen_cry.png"
image fs_diemen cry_dogless = "{{assets}}/sprite/diemen_cry_dogless.png"
image fs_diemen cry_shirtless = "{{assets}}/sprite/diemen_cry_shirtless.png"
image fs_diemen curious = "{{assets}}/sprite/diemen_curious.png"
image fs_diemen curious_dogless = "{{assets}}/sprite/diemen_curious_dogless.png"
image fs_diemen curious_shirtless = "{{assets}}/sprite/diemen_curious_shirtless.png"
image fs_diemen die_shirtless = "{{assets}}/sprite/diemen_die_shirtless.png"
image fs_diemen frown = "{{assets}}/sprite/diemen_frown.png"
image fs_diemen frown_dogless = "{{assets}}/sprite/diemen_frown_dogless.png"
image fs_diemen offer = "{{assets}}/sprite/diemen_offer.png"
image fs_diemen offer_dogless = "{{assets}}/sprite/diemen_offer_dogless.png"
image fs_diemen offer_dogless_resized = "{{assets}}/sprite/diemen_offer_dogless_resized.png"
image fs_diemen offer_shirtless = "{{assets}}/sprite/diemen_offer_shirtless.png"
image fs_diemen optimistic = "{{assets}}/sprite/diemen_optimistic.png"
image fs_diemen optimistic_dogless = "{{assets}}/sprite/diemen_optimistic_dogless.png"
image fs_diemen optimistic_dogless_resized = "{{assets}}/sprite/diemen_optimistic_dogless_resized.png"
image fs_diemen optimistic_scaled = "{{assets}}/sprite/diemen_optimistic_scaled.png"
image fs_diemen recoil = "{{assets}}/sprite/diemen_recoil.png"
image fs_diemen recoil_shirtless = "{{assets}}/sprite/diemen_recoil_shirtless.png"
image fs_diemen shock = "{{assets}}/sprite/diemen_shock.png"
image fs_diemen shock_shirtless = "{{assets}}/sprite/diemen_shock_shirtless.png"
image fs_diemen smile = "{{assets}}/sprite/diemen_smile.png"
image fs_diemen smile_dogless = "{{assets}}/sprite/diemen_smile_dogless.png"
image fs_diemen smile_dogless_resized = "{{assets}}/sprite/diemen_smile_dogless_resized.png"
image fs_diemen smile_scaled = "{{assets}}/sprite/diemen_smile_scaled.png"
image fs_diemen smile_shirtless = "{{assets}}/sprite/diemen_smile_shirtless.png"
image fs_diemen talk = "{{assets}}/sprite/diemen_talk.png"
image fs_diemen talk_dogless = "{{assets}}/sprite/diemen_talk_dogless.png"
image fs_diemen talk_dogless_resized = "{{assets}}/sprite/diemen_talk_dogless_resized.png"
image fs_diemen thinking = "{{assets}}/sprite/diemen_thinking.png"
image fs_diemen thinking_dogless = "{{assets}}/sprite/diemen_thinking_dogless.png"
image fs_diemen thinking_dogless_resized = "{{assets}}/sprite/diemen_thinking_dogless_resized.png"

init python:
    quirks["diemen"] = [("(.+)", "(| \g<1> |)")]
define fs_diemen = Character(name="DIEMEN", kind=hiveswap, image="diemen", show_blood="rust")

