init offset = 1
image fs_nikhee blankface = "{{assets}}/sprite/nikhee_blankface.png"
image fs_nikhee coward = "{{assets}}/sprite/nikhee_coward.png"
image fs_nikhee doiscareyou = "{{assets}}/sprite/nikhee_doiscareyou.png"
image fs_nikhee FLEXSTAR_01 = "{{assets}}/sprite/nikhee_FLEXSTAR_01.png"
image fs_nikhee FLEXSTAR_02 = "{{assets}}/sprite/nikhee_FLEXSTAR_02.png"
image fs_nikhee FLEXSTAR_03 = "{{assets}}/sprite/nikhee_FLEXSTAR_03.png"
image fs_nikhee getoutofmysight = "{{assets}}/sprite/nikhee_getoutofmysight.png"
image fs_nikhee hemhaw = "{{assets}}/sprite/nikhee_hemhaw.png"
image fs_nikhee kylorenlol = "{{assets}}/sprite/nikhee_kylorenlol.png"
image fs_nikhee listentome = "{{assets}}/sprite/nikhee_listentome.png"
image fs_nikhee lostleg = "{{assets}}/sprite/nikhee_lostleg.png"
image fs_nikhee MAYBE = "{{assets}}/sprite/nikhee_MAYBE.png"
image fs_nikhee milkflex = "{{assets}}/sprite/nikhee_milkflex.png"
image fs_nikhee NO = "{{assets}}/sprite/nikhee_NO.png"
image fs_nikhee notimpressed = "{{assets}}/sprite/nikhee_notimpressed.png"
image fs_nikhee offended = "{{assets}}/sprite/nikhee_offended.png"
image fs_nikhee proud = "{{assets}}/sprite/nikhee_proud.png"
image fs_nikhee ringstand = "{{assets}}/sprite/nikhee_ringstand.png"
image fs_nikhee smile = "{{assets}}/sprite/nikhee_smile.png"
image fs_nikhee THEBRAWNISEUM = "{{assets}}/sprite/nikhee_THEBRAWNISEUM.png"
image fs_nikhee weirdflexbutok = "{{assets}}/sprite/nikhee_weirdflexbutok.png"
image fs_nikhee weirdflexbutok_scowl = "{{assets}}/sprite/nikhee_weirdflexbutok_scowl.png"
define fs_nikhee = Character(name="NIKHEE", kind=hiveswap, image="nikhee", show_blood="blue")

