init offset = 1
image fs_wanshi betrayed = "{{assets}}/sprite/wanshi_betrayed.png"
image fs_wanshi claspshands = "{{assets}}/sprite/wanshi_claspshands.png"
image fs_wanshi curiosity = "{{assets}}/sprite/wanshi_curiosity.png"
image fs_wanshi eager = "{{assets}}/sprite/wanshi_eager.png"
image fs_wanshi expectant = "{{assets}}/sprite/wanshi_expectant.png"
image fs_wanshi fear = "{{assets}}/sprite/wanshi_fear.png"
image fs_wanshi gift = "{{assets}}/sprite/wanshi_gift.png"
image fs_wanshi hi = "{{assets}}/sprite/wanshi_hi.png"
image fs_wanshi intro_nothingtoseehere = "{{assets}}/sprite/wanshi_intro_nothingtoseehere.png"
image fs_wanshi intro_snitch = "{{assets}}/sprite/wanshi_intro_snitch.png"
image fs_wanshi intro_wanshiout = "{{assets}}/sprite/wanshi_intro_wanshiout.png"
image fs_wanshi OoO = "{{assets}}/sprite/wanshi_OoO.png"
image fs_wanshi rp = "{{assets}}/sprite/wanshi_rp.png"
image fs_wanshi sadsmile = "{{assets}}/sprite/wanshi_sadsmile.png"
image fs_wanshi shakingwithexcitement = "{{assets}}/sprite/wanshi_shakingwithexcitement.png"
image fs_wanshi sideye = "{{assets}}/sprite/wanshi_sideye.png"
image fs_wanshi teary = "{{assets}}/sprite/wanshi_teary.png"
image fs_wanshi ughlame = "{{assets}}/sprite/wanshi_ughlame.png"
image fs_wanshi woah = "{{assets}}/sprite/wanshi_woah.png"
image fs_wanshi youknowit = "{{assets}}/sprite/wanshi_youknowit.png"
define fs_wanshi = Character(name="WANSHI", kind=hiveswap, image="wanshi", show_blood="jade")

