define dave = Character(name="DAVE", what_color="#e00707", kind=pesterchum, image="dave")

image dave cellphone = Image("{{assets}}/sprite/Dave_cellphone.png", ypos=730)
image dave cellphone2 = Image("{{assets}}/sprite/Dave_cellphone2.png", ypos=730)
image dave concern = Image("{{assets}}/sprite/dave_concern.png", ypos=730)
image dave didyoujust = Image("{{assets}}/sprite/Dave_didyoujust.png", ypos=730)
image dave embarrased = Image("{{assets}}/sprite/Dave_embarrased.png", ypos=730)
image dave juice = Image("{{assets}}/sprite/Dave_juice.png", ypos=730)
image dave meh = Image("{{assets}}/sprite/dave_meh.png", ypos=730)
image dave nervouslaugh = Image("{{assets}}/sprite/Dave_nervouslaugh.png", ypos=730)
image dave neutral = Image("{{assets}}/sprite/dave_neutral.png", ypos=730)
image dave phase = Image("{{assets}}/sprite/dave_phase.png", ypos=730)
image dave rap1 = Image("{{assets}}/sprite/Dave_rap1.png", ypos=730)
image dave rap2 = Image("{{assets}}/sprite/Dave_rap2.png", ypos=730)
image dave reflection = Image("{{assets}}/sprite/Dave_reflection.png", ypos=730)
image dave smile = Image("{{assets}}/sprite/dave_smile.png", ypos=730)
image dave smooth1 = Image("{{assets}}/sprite/Dave_smooth1.png", ypos=730)
image dave smooth2 = Image("{{assets}}/sprite/Dave_smooth2.png", ypos=730)
image dave supermeh = Image("{{assets}}/sprite/Dave_supermeh.png", ypos=730)
image dave suspicious = Image("{{assets}}/sprite/Dave_suspicious.png", ypos=730)
image dave talk = Image("{{assets}}/sprite/dave_talk.png", ypos=730)
image dave talk2 = Image("{{assets}}/sprite/dave_talk2.png", ypos=730)
image dave talk3 = Image("{{assets}}/sprite/dave_talk3.png", ypos=730)
image dave talk4 = Image("{{assets}}/sprite/dave_talk4.png", ypos=730)
image dave talk5 = Image("{{assets}}/sprite/dave_talk5.png", ypos=730)
image dave talk6 = Image("{{assets}}/sprite/dave_talk6.png", ypos=730)
