define jade = Character(name="JADE", what_color="#4ac925", kind=pesterchum, image="jade")

image jade amazed = Image("{{assets}}/sprite/JADE_amazed.png", ypos=730)
image jade amused = Image("{{assets}}/sprite/JADE_amused.png", ypos=730)
image jade annoyed = Image("{{assets}}/sprite/JADE_annoyed.png", ypos=730)
image jade beaming = Image("{{assets}}/sprite/JADE_beaming.png", ypos=730)
image jade default = Image("{{assets}}/sprite/JADE_default.png", ypos=730)
image jade dumbfounded = Image("{{assets}}/sprite/JADE_dumbfounded.png", ypos=730)
image jade exploding1 = Image("{{assets}}/sprite/JADE_exploding1.png", ypos=730)
image jade exploding2 = Image("{{assets}}/sprite/JADE_exploding2.png", ypos=730)
image jade gun1 = Image("{{assets}}/sprite/JADE_gun1.png", ypos=730)
image jade gun2 = Image("{{assets}}/sprite/JADE_gun2.png", ypos=730)
image jade gun3 = Image("{{assets}}/sprite/JADE_gun3.png", ypos=730)
image jade gun4 = Image("{{assets}}/sprite/JADE_gun4.png", ypos=730)
image jade gun5 = Image("{{assets}}/sprite/JADE_gun5.png", ypos=730)
image jade gun6 = Image("{{assets}}/sprite/JADE_gun6.png", ypos=730)
image jade gun7 = Image("{{assets}}/sprite/JADE_gun7.png", ypos=730)
image jade gun8 = Image("{{assets}}/sprite/JADE_gun8.png", ypos=730)
image jade gun9 = Image("{{assets}}/sprite/JADE_gun9.png", ypos=730)
image jade handout = Image("{{assets}}/sprite/JADE_handout.png", ypos=730)
image jade handout2 = Image("{{assets}}/sprite/JADE_handout2.png", ypos=730)
image jade holdinghands amused = Image("{{assets}}/sprite/JADE_holdinghands_amused.png", ypos=730)
image jade holdinghands dissapointed = Image("{{assets}}/sprite/JADE_holdinghands_dissapointed.png", ypos=730)
image jade holdinghands sarcastic = Image("{{assets}}/sprite/JADE_holdinghands_sarcastic.png", ypos=730)
image jade huhh = Image("{{assets}}/sprite/JADE_huhh.png", ypos=730)
image jade Neutral = Image("{{assets}}/sprite/Jade_Neutral.png", ypos=730)
image jade sad = Image("{{assets}}/sprite/JADE_sad.png", ypos=730)
image jade Smiling = Image("{{assets}}/sprite/JADE_Smiling.png", ypos=730)
image jade surprised = Image("{{assets}}/sprite/JADE_surprised.png", ypos=730)
image jade thinking = Image("{{assets}}/sprite/JADE_thinking.png", ypos=730)
image jade upset angry = Image("{{assets}}/sprite/JADE_upset_angry.png", ypos=730)
image jade upset cheering up = Image("{{assets}}/sprite/JADE_upset_cheering_up.png", ypos=730)
image jade upset seething = Image("{{assets}}/sprite/JADE_upset_seething.png", ypos=730)
image jade upset shocked = Image("{{assets}}/sprite/JADE_upset_shocked.png", ypos=730)
image jade upset stressed = Image("{{assets}}/sprite/JADE_upset_stressed.png", ypos=730)
image jade upset tearing up = Image("{{assets}}/sprite/JADE_upset_tearing_up.png", ypos=730)
image jade weak smile = Image("{{assets}}/sprite/JADE_weak_smile.png", ypos=730)
image jade wistful = Image("{{assets}}/sprite/JADE_wistful.png", ypos=730)
image jade worried = Image("{{assets}}/sprite/JADE_worried.png", ypos=730)
