define john = Character(name="JOHN", what_color="#0715cd", kind=pesterchum, image="john")

image john AwkwardSmile = Image("{{assets}}/sprite/John_AwkwardSmile.png", ypos=730)
image john BlankStare = Image("{{assets}}/sprite/John_BlankStare.png", ypos=730)
image john Bleh = Image("{{assets}}/sprite/John_Bleh.png", ypos=730)
image john Concern = Image("{{assets}}/sprite/John_Concern.png", ypos=730)
image john CrossedArms = Image("{{assets}}/sprite/John_CrossedArms.png", ypos=730)
image john Defeated = Image("{{assets}}/sprite/John_Defeated.png", ypos=730)
image john Disguise = Image("{{assets}}/sprite/John_Disguise.png", ypos=730)
image john Displeased = Image("{{assets}}/sprite/John_Displeased.png", ypos=730)
image john FacePalm = Image("{{assets}}/sprite/John_FacePalm.png", ypos=730)
image john Forlorn = Image("{{assets}}/sprite/John_Forlorn.png", ypos=730)
image john Frown = Image("{{assets}}/sprite/John_Frown.png", ypos=730)
image john Frustrated = Image("{{assets}}/sprite/John_Frustrated.png", ypos=730)
image john Happy = Image("{{assets}}/sprite/John_Happy.png", ypos=730)
image john HYPE = Image("{{assets}}/sprite/John_HYPE.png", ypos=730)
image john ImNotCrazy = Image("{{assets}}/sprite/John_ImNotCrazy.png", ypos=730)
image john MildSurprise = Image("{{assets}}/sprite/John_MildSurprise.png", ypos=730)
image john Neutral = Image("{{assets}}/sprite/John_Neutral.png", ypos=730)
image john PerkUp = Image("{{assets}}/sprite/John_PerkUp.png", ypos=730)
image john Questioning = Image("{{assets}}/sprite/John_Questioning.png", ypos=730)
image john Shocked = Image("{{assets}}/sprite/John_Shocked.png", ypos=730)
image john Shrug = Image("{{assets}}/sprite/John_Shrug.png", ypos=730)
image john Suspicious = Image("{{assets}}/sprite/John_Suspicious.png", ypos=730)
image john Thinking = Image("{{assets}}/sprite/John_Thinking.png", ypos=730)
image john Whatever = Image("{{assets}}/sprite/John_Whatever.png", ypos=730)
image john Whoa = Image("{{assets}}/sprite/John_Whoa.png", ypos=730)
