define rose = Character(name="ROSE", what_color="#b536da", kind=pesterchum, image="rose")

image rose annoyed = Image("{{assets}}/sprite/ROSE_annoyed.png", ypos=730)
image rose cellphone = Image("{{assets}}/sprite/ROSE_cellphone.png", ypos=730)
image rose dejected = Image("{{assets}}/sprite/ROSE_dejected.png", ypos=730)
image rose disturbed = Image("{{assets}}/sprite/ROSE_disturbed.png", ypos=730)
image rose eyeroll = Image("{{assets}}/sprite/ROSE_eyeroll.png", ypos=730)
image rose frustrated = Image("{{assets}}/sprite/ROSE_frustrated.png", ypos=730)
image rose handout shocked = Image("{{assets}}/sprite/ROSE_handout_shocked.png", ypos=730)
image rose handout skeptical = Image("{{assets}}/sprite/ROSE_handout_skeptical.png", ypos=730)
image rose handraised = Image("{{assets}}/sprite/ROSE_handraised.png", ypos=730)
image rose holding wine = Image("{{assets}}/sprite/ROSE_holding_wine.png", ypos=730)
image rose mouthcovered shocked = Image("{{assets}}/sprite/ROSE_mouthcovered_shocked.png", ypos=730)
image rose neutral = Image("{{assets}}/sprite/ROSE_neutral.png", ypos=730)
image rose sheepish = Image("{{assets}}/sprite/ROSE_sheepish.png", ypos=730)
image rose smile = Image("{{assets}}/sprite/ROSE_smile.png", ypos=730)
image rose spitting = Image("{{assets}}/sprite/ROSE_spitting.png", ypos=730)
image rose umbrella Amused = Image("{{assets}}/sprite/ROSE_umbrella_Amused.png", ypos=730)
image rose umbrella ArmsCrossed = Image("{{assets}}/sprite/ROSE_umbrella_ArmsCrossed.png", ypos=730)
image rose umbrella Skeptical = Image("{{assets}}/sprite/ROSE_umbrella_Skeptical.png", ypos=730)
image rose umbrella Surprised = Image("{{assets}}/sprite/ROSE_umbrella_Surprised.png", ypos=730)
image rose umbrella Unamused = Image("{{assets}}/sprite/ROSE_umbrella_Unamused.png", ypos=730)
